/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ru.mtuci.kotlin-application-conventions")
}

dependencies {
    implementation(project(":core"))
    implementation("org.jsoup:jsoup:1.14.3")
    implementation("org.apache.poi:poi-ooxml:3.11")
}

application {
    // Define the main class for the application.
    mainClass.set("ru.mtuci.parser.AppKt")
}
