/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ru.mtuci.parser

import ru.mtuci.parser.rasp.parseRasp
import ru.mtuci.parser.teachers.parseTeachers

fun main() {
    parseRasp()
    parseTeachers()
}
