graphql:
  packages:
    - "ru.mtuci.models"
    - "ru.mtuci.backend.graphql"
    - "ru.mtuci.backend.generator"
    - "com.expediagroup.graphql.federation"
  playground:
    enabled: true
  introspection:
    enabled: true
server:
  http2:
    enabled: true